### ISSUE TITLE
WithCredentials is not a imported method of reddit

### ISSUE THREAD

**Issue by shuiRong** [vartanbeno/go-reddit#4]
> WithCredentials not declared by package reddit

I did can't find `WithCredentials` in [doc page](https://pkg.go.dev/github.com/vartanbeno/go-reddit@v1.0.0/reddit).
Is the README.md not update timely？

![image](https://user-images.githubusercontent.com/16076993/99896000-7cde7580-2cc7-11eb-98cc-5cbd6c69ca1c.png)

**Comment by vartanbeno** [comment]
Hey! Is it possible you're using `v1.0.0`? That option doesn't exist in that release; I've made lots of changes since. [Here](https://github.com/vartanbeno/go-reddit/blob/e1ce8a7a14bd42bf9c57a640d30da3a85d7a8cdd/README.md#usage) is the README.md from `v1.0.0`.

I'm gonna get around to tagging a new release soon. I'll leave a comment here when I do that!

**Comment by shuiRong** [comment]
Yes, `v1.0.0`.

**Comment by vartanbeno** [comment]
Hey! I just tagged a new release, [v2.0.0](https://github.com/vartanbeno/go-reddit/releases/tag/v2.0.0). Let me know if the issue persists.
